kind: pipeline
type: docker
name: default

steps:
- name: make
  image: alpine:3.15.0
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
    REGISTRY:
      from_secret: docker_registry
  commands:
  - wget https://ziglang.org/download/0.9.0/zig-linux-x86_64-0.9.0.tar.xz
  - tar x -C /usr/local -f zig-linux-x86_64-0.9.0.tar.xz
  - ln -s /usr/local/zig-linux-x86_64-0.9.0/zig /usr/local/bin/zig
  - apk add git
  - (cd codegen && zig build test)
  - zig build -Dfetch # implicitly does a codegen
  - zig build test
  - zig build -Dtarget=arm-linux
  - zig build -Dtarget=x86_64-windows
  - zig build -Dtarget=aarch64-linux
  - zig build -Dtarget=riscv64-linux
- name: notify
  image: plugins/matrix
  when:
    status:
    - success
    - failure
  settings:
    homeserver:
      from_secret: matrix-homeserver
    roomid:
      from_secret: matrix-room-id
    userid:
      from_secret: matrix-user-id
    accesstoken:
      from_secret: matrix-access-token
