kind: pipeline
type: docker
name: default

steps:
- name: make
  image: alpine:3.15.0
  environment:
    ZIG_VERSION: 0.9.1
  commands:
  # DRONE_STAGE_ARCH is fine, but we can't substitute directly because zig
  # uses x86_64 instead of amd64. They also use aarch64 instead of arm64.
  #
  # However, arm64/linux isn't quite fully tier 1 yet, so this is more of a
  # TODO: https://github.com/ziglang/zig/issues/2443
  #
  # DRONE_STAGE_ARCH=amd64
  # DRONE_STAGE_ARCH=arm64
  - wget https://ziglang.org/download/$${ZIG_VERSION}/zig-linux-x86_64-$${ZIG_VERSION}.tar.xz
  - tar x -C /usr/local -f zig-linux-x86_64-$${ZIG_VERSION}.tar.xz
  - ln -s /usr/local/zig-linux-x86_64-$${ZIG_VERSION}/zig /usr/local/bin/zig
  - apk add git
  - (cd codegen && zig build test)
  - zig build -Dfetch # implicitly does a codegen
  - zig build test
  - zig build -Dtarget=arm-linux
  - zig build -Dtarget=x86_64-windows
  - zig build -Dtarget=aarch64-linux
  - zig build -Dtarget=riscv64-linux
  - zig build -Dtarget=x86_64-macos
  - zig build -Dtarget=aarch64-macos
- name: notify
  image: plugins/matrix
  when:
    status:
    - success
    - failure
  settings:
    homeserver:
      from_secret: matrix-homeserver
    roomid:
      from_secret: matrix-room-id
    userid:
      from_secret: matrix-user-id
    accesstoken:
      from_secret: matrix-access-token
