name: Nightly zig version Build
on:
  push:
    branches:
      - 'zig-develop*'
jobs:
  build-zig-nightly:
    runs-on: ubuntu-latest
    if: ${{ github.env.GITEA_ACTIONS != 'true' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Zig
        uses: mlugg/setup-zig@v1.2.1
        with:
          version: master
      - name: Restore Zig caches
        uses: Hanaasagi/zig-action-cache@3954aae427f8b05914e08dfd79f15e1f2e435929
      - name: Run tests
        run: zig build test -Dbroken-windows --verbose
      - name: Run tests (release mode)
        run: zig build test -Doptimize=ReleaseSafe -Dbroken-windows --verbose # Github runners try to run the windows tests despite disabling foreign checks
      - name: Build example
        run: ( cd example && zig build ) # Make sure example builds
