name: aws-zig nightly build
on:
  push:
    branches:
      - 'zig-develop*'
jobs:
  build-zig-nightly:
    runs-on: ubuntu-latest
    if: ${{ github.env.GITEA_ACTIONS != 'true' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Zig
        uses: mlugg/setup-zig@v1.2.1
        with:
          version: master
      - name: Run tests
        run: zig build test -Dbroken-windows --verbose
      - name: Build example
        run: ( cd example && zig build ) # Make sure example builds
